package carShop;

/**
 * Created by employee on 10/21/15.
 */
public enum Options {
    OUTPUT_AVAILABLE_CARS,
    OUTPUT_MANAGERS,
    OUTPUT_DEALS,
    ADD_CAR,
    ENTER_BRAND,
    ENTER_CAR_NAME,
    ENTER_COST,
    ADD_MANAGER,
    ENTER_MANAGER_NAME,
    ENTER_MANAGER_SURNAME,
    BUY_CAR,
    CHOOSE_CAR,
    CHOOSE_MANAGER,
    CHOOSE_DATE,
    OUTPUT_BEST_MANAGER,
    CHOOSE_START_DATE,
    CHOOSE_END_DATE
}
